keys:
  - &desktop age1yyg7h7qytsqcfdj2nn66a8gkdgf74yuqv8wxvuhkffrmdmu8jcwqw5c25r
  - &spiritcrypt age174f925fc3nwr7ar4s86zvu44aufhm5lsw064vnhktkh8use79a8sevsn23
  - &laptop age1uyvl4uakcgjnllw8sqr5c5dzldah2jaxz9tneljjrngcvtmjvsvq03ryg7
  - &home_laptop age1rrt2jcn6csppu2xjfmzfcy2r922cenvn8gygkrct25mxwelhcpeqzrrj2j
  - &home_desktop age15uj6pjpu9ma36qg4gzp5guhp68qh9lashjahx39vyry8nsl9np7sz4vcfl
creation_rules:
  - path_regex: ^sops/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *desktop
        - *spiritcrypt
        - *laptop
  - path_regex: ^muni/sops/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *home_desktop
        - *home_laptop

