muni_bot.env: ENC[AES256_GCM,data:xBNpcTiNELSdxUptw1aWBTapYd12FlYLjXcT4ym9d2t3v9RO3pvdS2gCY2RSfknvXFpUQqXK//l7e35hQyhdLxHsfUU1lVllz5hXZRgmkbkkO2OV7RThTchIGNxLeaNm5LdRfU22lTugV36bdb3iZuB3qxur+sNa/+2rkiKPhghJFrfu6Ssfa9nhpvEniV6lBFhF3Yhu8kW3Cp+zqg9FN9raAyIsxG/jUqEfEGAPgvD/8rho8+8H7aGHIWfns9q7BY2/dIMd+PD2pdCwJNehg2b8rS505gyE+fOJyCJLTqPEupWyFsMn4KpUF9tZk+96N77YXOthjIJyGOZleGOwvCXTGNkIZRqv6HPKLXPHZyLrzinnXndduB58muU+73xypv+CGMvTNSSzomgYfbofHju11/gIWG+6buq5MjfTWLxIHRpmYmn44yYIGz2f/P1N7Nl4Xn4LaOTcn8vTFpQ708C2SklW9+HzisLKECmfurAYUxDXOu7DNgry4Fatx0frbS03I8s1XdJDozytZ3TzXnSaBMOUkUiHiS4vEy8hgxCiulnqaAkuMLV1J9fNCLPBsK0UCAOflrWJmJVkTvpEtXOZdK+gSX1hOAlYfncbnKbVsj8lfYbb9cvfgj7GZL1QLFlgt4VpfWXMO//m50gl,iv:KdBdRsrjXLco+oTBjzqEeHypj+tfo5ybjzwDVnQGDSc=,tag:7OwRG2hb9bBlWiwU0lufwA==,type:str]
cachix_token: ENC[AES256_GCM,data:Hr/9gh/kBmjzlsfgqDKh4NWV2OzQvJOLEyvPWGa2v0s5KCMxDTfBD5TU9cJmpDli4FHBZ8D5wgfB75l6jy+AaiIbIQIp8Aebk9bl3YmT27dZFprqJMZte/YhnsMI1R/LP/x4x6QqoPrFXFQ3l12TG0dOaF1T5ScCX+yfqJYYmb9zDIFkku09nuAj1BQ+7iXkBQ==,iv:QW8GEDR55zh4yVvmj0Ov8wzZLvWrXn7W1k7ThtwITzs=,tag:CZ4gijMCFbNEnQvcyjNohg==,type:str]
cachix_signing_key: ENC[AES256_GCM,data:gODm9FJv7hv29k4JejjGSZbA05mgS+CEpn94copYaoxc0A03oeVTeOMw06U9UcRkJDv7JDzX5opL+ibOXNa2oXoqisF/P0ARphJ1tHV6WNnpXQvPAgifMA==,iv:zUDgoDSMiRbuiP+5CgT+VKVt8W9/avPKj4jdxmcjeIQ=,tag:kcsw5zDBa83jAwGhvT0szA==,type:str]
sops:
    age:
        - recipient: age1yyg7h7qytsqcfdj2nn66a8gkdgf74yuqv8wxvuhkffrmdmu8jcwqw5c25r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VENROEx5YmZuUyt0a3RJ
            MmIrYUVlVGdhcVhYdDdGeng4OXdNOXg1WnhrCjg2VkZSeWFhOTVHbzh4RWhpQmVk
            UmpqN0NmN0dEbDdWaEZVY3BKRmtnZlUKLS0tIDR6WWN4YXJRa05Jb09OUHljaTlP
            anF4MElBcHBrSW1xa3IxN29hVUhUQ3MKFGx+NZqlMnA6ps1MPJpL7VD3Yg3najz5
            ww2mgogw83vqKvpoyNYA8rBtBDgwB7DOXxKnRJJyhJN6GHrT3C37OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174f925fc3nwr7ar4s86zvu44aufhm5lsw064vnhktkh8use79a8sevsn23
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbVFZc1Q3UHBXSnR5Y3Z4
            ZnIzVzJndW81cUx3UDNlTXdxeGFDMjlLTW00CmRRaU5LM3o3QXNSWklJV2NMbXgz
            RlpTR1hVVmNaWVNIMjkzQmVyMDBHSjQKLS0tIEptR21kdHpJZTM0ZkNFYS9Id1d0
            ZjdZeDFwUkNNZmxyMGlVZURmWXdQcTQKewOeKlrTf3AGpop8lwZsJBsszvAGF5Eh
            mHdUtqOvlPmE+mudkvEE6x5Fi8V4CBU8vq4A+lk1m09W3Lho779Jzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uyvl4uakcgjnllw8sqr5c5dzldah2jaxz9tneljjrngcvtmjvsvq03ryg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZkVPNyt1M1JUYTg0blFk
            VStqd0N4OXp4RnhDcnYyUFM2ZFkxZk15Z21rCmNod1h5a1Jic1RrOHNOTFB5UVFV
            a2lKYWNLeGVwcy94RnFjeWoxY2Y3dTAKLS0tIHpDbFBDSEZPMlkxZkdRNFFFWFA2
            WjN4VnFxdk9QeDF1RlRmQlNvSWdqYkkKNcpm7zCTycW0pSbOiHjkz75EXvqJi/kf
            EePfVP/2y+3AVfqBv4UDs7EV0w/5e362MrclsU4Q7zLu2MB/IqnxIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-25T20:13:06Z"
    mac: ENC[AES256_GCM,data:hJGsBZC7GpjY/GpSvi2AIGIJ1F5HfcXi1XD8kb7rFxqF/fb628Uieebi9rEtGg/lrNt4UTImqJEOwdDaSUaAAkImStbiFrUcCBNeHtmufnfVMPU+JKlD+biF0PQT43BbEM0pZrMyH+lgVPn8XFJLQ0RLog/YzhodUtgJC/gk6Xk=,iv:rjoPLQQYFZoIZFmKqSt0W0S4LkiD61yiq+Mnfdo/jbw=,tag:JcgPmXVRwn20t4kmR6Vv3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
