muni_bot.env: ENC[AES256_GCM,data:xBNpcTiNELSdxUptw1aWBTapYd12FlYLjXcT4ym9d2t3v9RO3pvdS2gCY2RSfknvXFpUQqXK//l7e35hQyhdLxHsfUU1lVllz5hXZRgmkbkkO2OV7RThTchIGNxLeaNm5LdRfU22lTugV36bdb3iZuB3qxur+sNa/+2rkiKPhghJFrfu6Ssfa9nhpvEniV6lBFhF3Yhu8kW3Cp+zqg9FN9raAyIsxG/jUqEfEGAPgvD/8rho8+8H7aGHIWfns9q7BY2/dIMd+PD2pdCwJNehg2b8rS505gyE+fOJyCJLTqPEupWyFsMn4KpUF9tZk+96N77YXOthjIJyGOZleGOwvCXTGNkIZRqv6HPKLXPHZyLrzinnXndduB58muU+73xypv+CGMvTNSSzomgYfbofHju11/gIWG+6buq5MjfTWLxIHRpmYmn44yYIGz2f/P1N7Nl4Xn4LaOTcn8vTFpQ708C2SklW9+HzisLKECmfurAYUxDXOu7DNgry4Fatx0frbS03I8s1XdJDozytZ3TzXnSaBMOUkUiHiS4vEy8hgxCiulnqaAkuMLV1J9fNCLPBsK0UCAOflrWJmJVkTvpEtXOZdK+gSX1hOAlYfncbnKbVsj8lfYbb9cvfgj7GZL1QLFlgt4VpfWXMO//m50gl,iv:KdBdRsrjXLco+oTBjzqEeHypj+tfo5ybjzwDVnQGDSc=,tag:7OwRG2hb9bBlWiwU0lufwA==,type:str]
cachix_token: ENC[AES256_GCM,data:Hr/9gh/kBmjzlsfgqDKh4NWV2OzQvJOLEyvPWGa2v0s5KCMxDTfBD5TU9cJmpDli4FHBZ8D5wgfB75l6jy+AaiIbIQIp8Aebk9bl3YmT27dZFprqJMZte/YhnsMI1R/LP/x4x6QqoPrFXFQ3l12TG0dOaF1T5ScCX+yfqJYYmb9zDIFkku09nuAj1BQ+7iXkBQ==,iv:QW8GEDR55zh4yVvmj0Ov8wzZLvWrXn7W1k7ThtwITzs=,tag:CZ4gijMCFbNEnQvcyjNohg==,type:str]
cachix_signing_key: ENC[AES256_GCM,data:gODm9FJv7hv29k4JejjGSZbA05mgS+CEpn94copYaoxc0A03oeVTeOMw06U9UcRkJDv7JDzX5opL+ibOXNa2oXoqisF/P0ARphJ1tHV6WNnpXQvPAgifMA==,iv:zUDgoDSMiRbuiP+5CgT+VKVt8W9/avPKj4jdxmcjeIQ=,tag:kcsw5zDBa83jAwGhvT0szA==,type:str]
nix_builder_private_key: ENC[AES256_GCM,data:ss79BNhjsFQo4VSHEzg60YmPK/DACR4aDbiJ06wBl6r0IQqz7WHxkwR2tPqU1sXNUBSR0s7iE2OwTLN75ye5CzwfEU2V3ni1iyhfSWN/hgCNJA+BTr3W39G/cMIatMVGX1wIbIlDJj9jGoVz5d8+d5io4CVOCy7BXFz0YQ81chHFb6QSBxy3r0JYs6jBxZmezZ3EhdGIbsSTIy4abP+8ERZyM0dgRkwy4RrQKdlZw6vnedL85cJlFHPPt/EJKbKWVBj8YM7cCMG+oWXQifid6erfQjkFVkPqWtk2ipAbiQ3FBoGsS0SWBZ2bJHiuRvRAcuUlblTRdCh1Vq5rhJfjsuMfHP1RUTgcMkphVVuQmkzbkY2Zm81H/R0L1qHHoxXVzPlteUHJbDqwAZoxspm4vm+kTzerQpdocawb+87iK+9i4de0ZJ1KTjZ4q+dk56Bd8Q/fYtwuUYOu+9DfdCggbR+CCoOYMBReV1XKBdLRpC0r5/zW5M3waJK1g/1VxRG4wfR/kwVXz0YMyAJ4lLy+,iv:9+/Ifj3CrFo7UvSWsyXhyaxiC4j958hKADH7OZXPFKo=,tag:84Ai2imOxco4LN767pJwug==,type:str]
nix_builder_passwd: ENC[AES256_GCM,data:quYJjsDzS18Z6V5r/cgOojSwvLGyoAWtFTyDiTwOZeBoTeBkcDkSOWPPh1t59gf+aAdyJT2PlY3PnzGd1beBXDKc+7nVwOCL3w==,iv:lvfK+dQsrkkaZyFJa+MM+4d/p3W6Jskf1jDO5fw7NnU=,tag:Z6gOGRuOAJx272kxVmRLmg==,type:str]
nix_serve_secret_key: ENC[AES256_GCM,data:G3JA+esBS/XOPvWuzdZAFKWbNkaBNL6wMaymZ8tU+4p8u9teRtaK8zaos4rmZr29T+sn9ypf/dIrkBBDidIYflcVW+jzAwP7ScU15Q1joOe1V5wRcg6LjTCN/Zxvss210KaLTroSawcObaU5rpMK,iv:NFq7cSsythBl6ckl2SOVuu2JLZbZ5WpjTvxBeRNwHf8=,tag:MPxL2IutVpTGfx/MMcBp3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyg7h7qytsqcfdj2nn66a8gkdgf74yuqv8wxvuhkffrmdmu8jcwqw5c25r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VENROEx5YmZuUyt0a3RJ
            MmIrYUVlVGdhcVhYdDdGeng4OXdNOXg1WnhrCjg2VkZSeWFhOTVHbzh4RWhpQmVk
            UmpqN0NmN0dEbDdWaEZVY3BKRmtnZlUKLS0tIDR6WWN4YXJRa05Jb09OUHljaTlP
            anF4MElBcHBrSW1xa3IxN29hVUhUQ3MKFGx+NZqlMnA6ps1MPJpL7VD3Yg3najz5
            ww2mgogw83vqKvpoyNYA8rBtBDgwB7DOXxKnRJJyhJN6GHrT3C37OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174f925fc3nwr7ar4s86zvu44aufhm5lsw064vnhktkh8use79a8sevsn23
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbVFZc1Q3UHBXSnR5Y3Z4
            ZnIzVzJndW81cUx3UDNlTXdxeGFDMjlLTW00CmRRaU5LM3o3QXNSWklJV2NMbXgz
            RlpTR1hVVmNaWVNIMjkzQmVyMDBHSjQKLS0tIEptR21kdHpJZTM0ZkNFYS9Id1d0
            ZjdZeDFwUkNNZmxyMGlVZURmWXdQcTQKewOeKlrTf3AGpop8lwZsJBsszvAGF5Eh
            mHdUtqOvlPmE+mudkvEE6x5Fi8V4CBU8vq4A+lk1m09W3Lho779Jzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uyvl4uakcgjnllw8sqr5c5dzldah2jaxz9tneljjrngcvtmjvsvq03ryg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZkVPNyt1M1JUYTg0blFk
            VStqd0N4OXp4RnhDcnYyUFM2ZFkxZk15Z21rCmNod1h5a1Jic1RrOHNOTFB5UVFV
            a2lKYWNLeGVwcy94RnFjeWoxY2Y3dTAKLS0tIHpDbFBDSEZPMlkxZkdRNFFFWFA2
            WjN4VnFxdk9QeDF1RlRmQlNvSWdqYkkKNcpm7zCTycW0pSbOiHjkz75EXvqJi/kf
            EePfVP/2y+3AVfqBv4UDs7EV0w/5e362MrclsU4Q7zLu2MB/IqnxIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-02T18:03:41Z"
    mac: ENC[AES256_GCM,data:aaCm4hbFbIQH4jrI4KXMNYOGEgiG9npEaVkXKn9HGCxqKLptvS50lseLZVKgLIXxoXzfnYJZdqv7OIq08vAZ6NDwMCi1nnBPECEwNcJGkvkx7Yp4CKYyyNg8Y2rcSceqS1WIgfM22AVFm75YA/5RxYZ3AyaG2buG2VphR/qGXk8=,iv:Lve8RdzhEZeVbbMtZgmKqP8e6CzlhyWFFea9tQrCpxs=,tag:5Ak7nSwplEuyTrSI5f6y5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.10.1
