taskwarrior_secrets: ENC[AES256_GCM,data:79Bg1/lyFmUodE+YLQjxmob0JlL6DHvyg4PUxL99E+3joLNUVr+HDf752s3nmm7SXk8nowo35NCoKcug8w9NDo5MnFd4QP65K2XBoPAtLiji2OGxzTZQ1Ft0eIri07hu4BKavFA7QKJdIdBp,iv:r6plsNYaX21fadbc2PJtM/pAMpMzgeklgvJFcEKy5qI=,tag:+RwrRgPJBZG1SDCA1CCyJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uj6pjpu9ma36qg4gzp5guhp68qh9lashjahx39vyry8nsl9np7sz4vcfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOEppWGFJV21BRHErcHFF
            akJQVkFkSGhEOUsxWlc4SmY0bkdTdU4vT1dZCkswU1VZRXVxQi9La2paaVU4RS9i
            R1JHUUtvSmFqYkphbkdvOCtuY3ByOXcKLS0tIGg3dFNEcGdrWEhxWUhDZHA2akNG
            OThhUjZLVXovQ1pwS2g0OE5XQ0Jacm8KCLmUA8zAbtzqUwAZ7AY8F4487xwCjV6J
            4+NKTIzQ19ViZbp8ovGj+LEKzRu85sQbhAuSQMl14CJ3T7Dn2r7g3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrt2jcn6csppu2xjfmzfcy2r922cenvn8gygkrct25mxwelhcpeqzrrj2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNHJvODI1VWQybXlKK1Ix
            ZGhJdlpWcDAxYVlTUFAxRnR4eW5pYU9VUmtnCnFaZDdHd3dvNTM4M1FNRXZLeldj
            VFI1NDdSQW5HbkRVRlVCbjl2QUpVYlkKLS0tIGNTcFJzUWF6b2V1Tll2emNEU1ZG
            QUthYlJmaThDTUdvQWdWK0tBS1dwRjQKNrmR8hYksDNuhOZKE16lWDBNmW3C0Hof
            wQMr92M3i/zs+r3wIzsn5g1StrJ14BNv/tR5q8UbFgJJndrCuqbMvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T23:47:02Z"
    mac: ENC[AES256_GCM,data:b+VBiGWV+zyZIy923yeZ0auJ/lGBsE5qrQCV+cuR50m++ROFlCyFrt7kfeBfUSKsJNJuv9dVUOEZ0Lb3n4J/dNRvGH0i6CAS5ga5y7CIvkbW+EqDWS9fW+C+ARvdbN0IBPyYGrSfEWUZ8KjxMjFAOOIlTIcmxKy5oxx70uvo6dk=,iv:sRAuufCSf2jxB5T2V/nfSmp4n2fjUSaOUkDls96L40Q=,tag:6wNirLX3F55tLpllTaYnnA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
