taskwarrior_secrets: ENC[AES256_GCM,data:79Bg1/lyFmUodE+YLQjxmob0JlL6DHvyg4PUxL99E+3joLNUVr+HDf752s3nmm7SXk8nowo35NCoKcug8w9NDo5MnFd4QP65K2XBoPAtLiji2OGxzTZQ1Ft0eIri07hu4BKavFA7QKJdIdBp,iv:r6plsNYaX21fadbc2PJtM/pAMpMzgeklgvJFcEKy5qI=,tag:+RwrRgPJBZG1SDCA1CCyJQ==,type:str]
liberdus_mrconfig: ENC[AES256_GCM,data:dJFaTgKVfNkH6YO5wgqetMYuo649Mb6mOFDNt8FQmkMBi7qcLV0aoMZfc0TN5vU1rVPoFsJt7CO9Zi7STrlOUL8wc3+W5TCIRULr5CGNcg/3nqMXiU1JtecXCmFHSbsxcLRqG87BpD3aow4iukDOXASqh44wASXUweH47yK6xs7Rj+S3HdYIWhAs7vXkC9EQykiy5Q0gaKLTA5s5w6sLO1ZJsK45Mjt7p1exKkwmHDC7CCc+1jUlfUppM+gqFrMQ4YP4rPG37vZjJJXRCagNF02f4btcTM5EVC0gwSdUUMomj1Z06HfzuDmKO+OdDOYxq8cgUOiAQZZEkPWQmwi7LGF7RSpYraR6GWrLquawygp7bjtXGw37EqEhtwfy2saDHM3QBl2EwtKfuLu517o6dyL98T5jBYTnyVlbzYm3G2ygx/0HO0GOCAs+YUhT663i/93zxHh998PqDOjDZLHDgavWRpK5GbI+sLF/1kNfhzItdikULmxHts4cg70lpoF5uoJqHc3Fn0milm0qTSTUGlhAu53TWV/FWZVjjnj290W7szypD+6/41gSWBY1yqbGzbrAT0fL84hub4S92iDPPq3hDHmw7EEReS6bj1iRaJKHRQ6wcR+ESHtuTkcnGzyodKdRuR0qn6XQIV6ccGrhAfpPv99DabkHBEzNkufx4IC2cBDyvpzxAE1UZnpJCVrBIBwlBU/itkVZtd/yg6zHpodjt+8uzwctwS7EfYykFMHp1aMtZaqM69w3AjsKj+xV4VGfqdFvbPSiWl6svOsg94xogqhkZCSy7wdKmAM0777f2BmjPSId2vW5Un8+YJEfhsXjyrbG1MR7Fq6QzDSJJgxzCRuq365ZYAghXVr1wCIe1F/5Ns9ih/RC8kFb6kwz4vAz5bHDu/l/GgjvXfw/gBXTmzTyLnzsMp9mfRZ9MlDT3y3CNj4UQ5ZnWm964eiEVIqkiywN5KT8lUL6r6fjKYR/umijTCaWPT8qxN3CwtDWTg==,iv:ygTd056iQIA204pk9qcE3GiNfMjI9NSaSwz+8Yor13U=,tag:HVFOizs5lZkb0MapWp96hA==,type:str]
apollo_mrconfig: ENC[AES256_GCM,data:ancCVZdmLm+EUUM6XLcn7r0JFHR6rFWcmqmMyOI07Q9B6vIS7DFQoyKlL+QE8ojfBzt6qY1aFdYqSC1yMaQT+gq3LzOIVs2I9mvfhdIdFaeA0nvxxuPCJ9UFh2a+wkhKQSmHDXqbCFtxYRAf9dvo6zHZPlzZdnLKyn4lgnyzGkR6uzmJ3YB2RTA8Mrp6BXhs2Eae/jfKPhcWfQ6ILyAGUi/wku5T33q6QF3GKVXgNKlkw9oSb1cFQaRDxrKx0jAlXuEFNsPi9NiZsARpIzYTlH7OZ7QqgJk/1fcAsE/3Iwi7RzeCpKrMnKXss5IhBucqX+ysaWrHY09Rf1h6HZ34l1rvIFtqJ7sXIhuTEx2YgplwMTPWbH3IZzDwJzFU+qjYUdB9nHs=,iv:GNQewZ2v8KsuUnDo7nOlj0cpW8lyFbrAfEz1RtLb7sc=,tag:ehcsqfuTV9A2UZZSMyiV+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uj6pjpu9ma36qg4gzp5guhp68qh9lashjahx39vyry8nsl9np7sz4vcfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTVVyb0lTcC9VZnp2dWxh
            VWFvOG9SdjBJY0cwbTVMU2VWVHNEV3Ywa3pFCjVoTmluOEY3dFJYR1lmSFc5aWpi
            SlFBallmWGZweWk0OVZIeXU3c3pPVUUKLS0tIDVMS3lVUHplSmZuWFBCUmUyOHZY
            TFVJOVFTTDdCc05lVDM4SEd1YUs1cmMK0iMws2Z2Lb5p6gbtcFjsKt+cHJ0dXQoj
            vu0G+F65yRkBA7imzHABg4wkLI8apGswqqQDSguTDhE2FI5rvWTS/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrt2jcn6csppu2xjfmzfcy2r922cenvn8gygkrct25mxwelhcpeqzrrj2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VDk3RXdZTTBOUlNGS1Bh
            NWdiakNvWGk2QUh4RkgrM1NUWjl1MUlWNm00CkNRdW1GS3habURZSDh2SUdNV0lu
            RU5aWlZXcVEwY2liZVFuNTZzcW5aRDgKLS0tIHpRVklZWGpsQ3k5Nk90aUsydE1B
            WFNFRlgyVWRmbkNHdm9KU1krd1RtaU0KacMqgmtg1lzjb63MYY7tL4qeSir2z0Ci
            XRYF8G9FtvnuWtEAhrbL9mCuT5GR7J6xiFxRuhmWkXtXcjsFYRxD0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rvzveql3utzaq6ve2gt09dezarqrs9nkrj3whmps8xdn85r5v9sstjgfzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3lHK3FRS1dPQ0E0ZWEr
            d0NJZ1VDQW1Ma0kvV0FjcHNZSXhIYm5kTjN3CmpUODVvUzI2QTFsRktMQjFTTzU5
            NVBQa1VjWTczNmhSRXNJMHNSZ2xObzAKLS0tIEVhbllpS3NsakpVRkJPaTN1WGgw
            Z29IZ21mWWV6dFVKNndEcG9iRkFGOTgKb5chwQJmsraiPvjh9Zlx0OeM5KY49C+x
            vcWcfDOZEwyNz4TjxFmwZcNwOR05pzCZYFnX4llUBr+fhQ3LhdWOYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T19:07:45Z"
    mac: ENC[AES256_GCM,data:85h/+9oyEYiQn2MqPbvJI6nkdRP6cAA/PM9Z2chM/cwH5aGIwzjJ6ISQKJF6ucLrUCfcQL8CZEkcD7Fbb/X1Fq9Ir7QnEhrLCpucYnhkQIegdBu++Nr/Kn6+kv3IJp35vW0YcvoKaPwxSNW655Yb4Z2gt0T+mpi0rgNERPTPsZc=,iv:FjrAlEFbirOHa8TeJlImAco6q8XkCtPowRb6XCP3vwo=,tag:6GvoGXFlcsOdp+PF+mD0yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
