taskwarrior_secrets: ENC[AES256_GCM,data:79Bg1/lyFmUodE+YLQjxmob0JlL6DHvyg4PUxL99E+3joLNUVr+HDf752s3nmm7SXk8nowo35NCoKcug8w9NDo5MnFd4QP65K2XBoPAtLiji2OGxzTZQ1Ft0eIri07hu4BKavFA7QKJdIdBp,iv:r6plsNYaX21fadbc2PJtM/pAMpMzgeklgvJFcEKy5qI=,tag:+RwrRgPJBZG1SDCA1CCyJQ==,type:str]
liberdus_mrconfig: ENC[AES256_GCM,data:dJFaTgKVfNkH6YO5wgqetMYuo649Mb6mOFDNt8FQmkMBi7qcLV0aoMZfc0TN5vU1rVPoFsJt7CO9Zi7STrlOUL8wc3+W5TCIRULr5CGNcg/3nqMXiU1JtecXCmFHSbsxcLRqG87BpD3aow4iukDOXASqh44wASXUweH47yK6xs7Rj+S3HdYIWhAs7vXkC9EQykiy5Q0gaKLTA5s5w6sLO1ZJsK45Mjt7p1exKkwmHDC7CCc+1jUlfUppM+gqFrMQ4YP4rPG37vZjJJXRCagNF02f4btcTM5EVC0gwSdUUMomj1Z06HfzuDmKO+OdDOYxq8cgUOiAQZZEkPWQmwi7LGF7RSpYraR6GWrLquawygp7bjtXGw37EqEhtwfy2saDHM3QBl2EwtKfuLu517o6dyL98T5jBYTnyVlbzYm3G2ygx/0HO0GOCAs+YUhT663i/93zxHh998PqDOjDZLHDgavWRpK5GbI+sLF/1kNfhzItdikULmxHts4cg70lpoF5uoJqHc3Fn0milm0qTSTUGlhAu53TWV/FWZVjjnj290W7szypD+6/41gSWBY1yqbGzbrAT0fL84hub4S92iDPPq3hDHmw7EEReS6bj1iRaJKHRQ6wcR+ESHtuTkcnGzyodKdRuR0qn6XQIV6ccGrhAfpPv99DabkHBEzNkufx4IC2cBDyvpzxAE1UZnpJCVrBIBwlBU/itkVZtd/yg6zHpodjt+8uzwctwS7EfYykFMHp1aMtZaqM69w3AjsKj+xV4VGfqdFvbPSiWl6svOsg94xogqhkZCSy7wdKmAM0777f2BmjPSId2vW5Un8+YJEfhsXjyrbG1MR7Fq6QzDSJJgxzCRuq365ZYAghXVr1wCIe1F/5Ns9ih/RC8kFb6kwz4vAz5bHDu/l/GgjvXfw/gBXTmzTyLnzsMp9mfRZ9MlDT3y3CNj4UQ5ZnWm964eiEVIqkiywN5KT8lUL6r6fjKYR/umijTCaWPT8qxN3CwtDWTg==,iv:ygTd056iQIA204pk9qcE3GiNfMjI9NSaSwz+8Yor13U=,tag:HVFOizs5lZkb0MapWp96hA==,type:str]
apollo_mrconfig: ENC[AES256_GCM,data:XJ5Ah7+qO8i5uO3TqBU5RZP0er06sQ9l6SFNAoq0gj7+xQlYMKr6lJweMjchQaceH2GtAzglYmlBREBgS4/kGmSXobzbFY4f7xuinO2LrqZdQdLrmYJs+BSlK5mYeXbFxuP95TyWWHsHIo5PUpd4vgaSeOa3rwlL/b1XWVdjdJPTfFJicDf+bzhWv/LyZtAq1VcB94UITulNTVK1UrLfwyLvQ66zK/QTvt84VfNh4M+wnj/hYSpsi/r5bar+qEcXIUoeTmwRXbtg+/UvdVzFSX0Iv/6j6SfOqHt90MzyuYCBs1kBiMyGSJfjkE+4q7TLXPo0xEQVXKIcc7pb/lv4iT6CHJqFryTSBp1zeJAvU8ydnGEsgQq5,iv:xj7Qfx9uXLozxJg2nmLF65fPUluOafsB4JmDAf+9JEQ=,tag:5tj6NrMB9aSgugxQ+RctMA==,type:str]
pay_respects_anthropic_api_key: ENC[AES256_GCM,data:NXZKs0+wg2nIikOG34zNc9J58upJAGtql8e5z/PvrM33qwZr1k4xqs7QKRQQ4WGfUW8+r/l9i5viAOk5IKLwl0Bxhqy+XAKf1D72WEwEnWk/HKIY+mJV9BVJ2J9UaJfIgRrsbZJ6cPEUCceb,iv:OtHc9pkoSuD0yb5eAbD9yaSO0KrKLFW2CC4jAeZqApg=,tag:6CrQZkbohdVLXYeIiZZTkQ==,type:str]
fish_ai_ini: ENC[AES256_GCM,data:JVR7nMTzaNwyY5fU0I3y+Att6xiEruIwanOEh5hZIAMUWjAyCksISmBmxKYSWLYw98MugAADeYbI3Jns8bDgZmgCp2rlHvcwhjQXD9WlTMAw3IEGKklYVkm725dxJSaPBciqysveuoFHXYjT/Dj6Q+rfSwBRcz83HLgaBOE8rBBX2vE3PnybKLh4RsKJxbS1Cj21A3NgYt4=,iv:EdHsPalNBjO1wNcMHX0JSE8ftF6a645dQ4ozp+yjM4E=,tag:3aWYatuhUws2QizVc96FPA==,type:str]
oco_api_key: ENC[AES256_GCM,data:Xi71FH5Uz3Wr0omweYDMBVe18jMDIXpHXe4oPdAoxuKuxQzLyY7ROsH600b1Y4vCHf4ITE+yRSRHmsXHliTcmhuotiy2bU+KmVCPL/Q2lUQDd1ylBiQD9rmPzsRWzFKWc/aSVZr9V2vpEnNi,iv:w6U1tc7T2b7/28HhFisC5wKxvUURkbsOJTLAhI9xu/4=,tag:hRHkIwLa5X9YypC4e7Dl3g==,type:str]
github_pat: ENC[AES256_GCM,data:hCeZyO82rSK9IyVHnIcBs246P2ksfkJOR0BE4NHkaYrYP+7ciF9Ev/xV0XULgL7cJ7WCHKkVeZC8iNEgXMFv6FpC0NGsd9IuNxydUFWAuRD2Urr1Rih6NPOn8YPm,iv:gVAGXNQ6rpNgxtQUOSEDOBA8runSTqh0kUA60OC1qvc=,tag:ymJnH18dBzIWhyoUhzm8mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uj6pjpu9ma36qg4gzp5guhp68qh9lashjahx39vyry8nsl9np7sz4vcfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTVVyb0lTcC9VZnp2dWxh
            VWFvOG9SdjBJY0cwbTVMU2VWVHNEV3Ywa3pFCjVoTmluOEY3dFJYR1lmSFc5aWpi
            SlFBallmWGZweWk0OVZIeXU3c3pPVUUKLS0tIDVMS3lVUHplSmZuWFBCUmUyOHZY
            TFVJOVFTTDdCc05lVDM4SEd1YUs1cmMK0iMws2Z2Lb5p6gbtcFjsKt+cHJ0dXQoj
            vu0G+F65yRkBA7imzHABg4wkLI8apGswqqQDSguTDhE2FI5rvWTS/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrt2jcn6csppu2xjfmzfcy2r922cenvn8gygkrct25mxwelhcpeqzrrj2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VDk3RXdZTTBOUlNGS1Bh
            NWdiakNvWGk2QUh4RkgrM1NUWjl1MUlWNm00CkNRdW1GS3habURZSDh2SUdNV0lu
            RU5aWlZXcVEwY2liZVFuNTZzcW5aRDgKLS0tIHpRVklZWGpsQ3k5Nk90aUsydE1B
            WFNFRlgyVWRmbkNHdm9KU1krd1RtaU0KacMqgmtg1lzjb63MYY7tL4qeSir2z0Ci
            XRYF8G9FtvnuWtEAhrbL9mCuT5GR7J6xiFxRuhmWkXtXcjsFYRxD0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rvzveql3utzaq6ve2gt09dezarqrs9nkrj3whmps8xdn85r5v9sstjgfzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3lHK3FRS1dPQ0E0ZWEr
            d0NJZ1VDQW1Ma0kvV0FjcHNZSXhIYm5kTjN3CmpUODVvUzI2QTFsRktMQjFTTzU5
            NVBQa1VjWTczNmhSRXNJMHNSZ2xObzAKLS0tIEVhbllpS3NsakpVRkJPaTN1WGgw
            Z29IZ21mWWV6dFVKNndEcG9iRkFGOTgKb5chwQJmsraiPvjh9Zlx0OeM5KY49C+x
            vcWcfDOZEwyNz4TjxFmwZcNwOR05pzCZYFnX4llUBr+fhQ3LhdWOYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T05:44:01Z"
    mac: ENC[AES256_GCM,data:dkjPPnXbTH3syLe1+D5wpIlrvMznsC0pXO1YEtytMr4gXOINqifNFQz0O3GUtd9X8292rLwGhvAzOVvK73OtSb/xNkwnMn/eraO+Z8Imp9FFYU/yU+kukGE8PK4VmQEdzb2f1zaBZ2+8Cyhvq4P2F9pw46UTEGRICqp9xM39vV8=,iv:OtjMd3qNp5mv/yRiExeLYxFYdtlDhD3Lkwg4o3Fds6E=,tag:UBeng/zIKxe6mtd4ZM930w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
