taskwarrior_secrets: ENC[AES256_GCM,data:79Bg1/lyFmUodE+YLQjxmob0JlL6DHvyg4PUxL99E+3joLNUVr+HDf752s3nmm7SXk8nowo35NCoKcug8w9NDo5MnFd4QP65K2XBoPAtLiji2OGxzTZQ1Ft0eIri07hu4BKavFA7QKJdIdBp,iv:r6plsNYaX21fadbc2PJtM/pAMpMzgeklgvJFcEKy5qI=,tag:+RwrRgPJBZG1SDCA1CCyJQ==,type:str]
liberdus_mrconfig: ENC[AES256_GCM,data:dJFaTgKVfNkH6YO5wgqetMYuo649Mb6mOFDNt8FQmkMBi7qcLV0aoMZfc0TN5vU1rVPoFsJt7CO9Zi7STrlOUL8wc3+W5TCIRULr5CGNcg/3nqMXiU1JtecXCmFHSbsxcLRqG87BpD3aow4iukDOXASqh44wASXUweH47yK6xs7Rj+S3HdYIWhAs7vXkC9EQykiy5Q0gaKLTA5s5w6sLO1ZJsK45Mjt7p1exKkwmHDC7CCc+1jUlfUppM+gqFrMQ4YP4rPG37vZjJJXRCagNF02f4btcTM5EVC0gwSdUUMomj1Z06HfzuDmKO+OdDOYxq8cgUOiAQZZEkPWQmwi7LGF7RSpYraR6GWrLquawygp7bjtXGw37EqEhtwfy2saDHM3QBl2EwtKfuLu517o6dyL98T5jBYTnyVlbzYm3G2ygx/0HO0GOCAs+YUhT663i/93zxHh998PqDOjDZLHDgavWRpK5GbI+sLF/1kNfhzItdikULmxHts4cg70lpoF5uoJqHc3Fn0milm0qTSTUGlhAu53TWV/FWZVjjnj290W7szypD+6/41gSWBY1yqbGzbrAT0fL84hub4S92iDPPq3hDHmw7EEReS6bj1iRaJKHRQ6wcR+ESHtuTkcnGzyodKdRuR0qn6XQIV6ccGrhAfpPv99DabkHBEzNkufx4IC2cBDyvpzxAE1UZnpJCVrBIBwlBU/itkVZtd/yg6zHpodjt+8uzwctwS7EfYykFMHp1aMtZaqM69w3AjsKj+xV4VGfqdFvbPSiWl6svOsg94xogqhkZCSy7wdKmAM0777f2BmjPSId2vW5Un8+YJEfhsXjyrbG1MR7Fq6QzDSJJgxzCRuq365ZYAghXVr1wCIe1F/5Ns9ih/RC8kFb6kwz4vAz5bHDu/l/GgjvXfw/gBXTmzTyLnzsMp9mfRZ9MlDT3y3CNj4UQ5ZnWm964eiEVIqkiywN5KT8lUL6r6fjKYR/umijTCaWPT8qxN3CwtDWTg==,iv:ygTd056iQIA204pk9qcE3GiNfMjI9NSaSwz+8Yor13U=,tag:HVFOizs5lZkb0MapWp96hA==,type:str]
apollo_mrconfig: ENC[AES256_GCM,data:08z/HYy8Njoq3n0iqqKyvAHVL8+g9fdK/uGLxM3GwOlORgTPMLewnXey/Jj3bIGyVyENwrf0RahtOxu+tgRRNRW7djBcs9p9TEpbObIwx1CldHZZGv4kVHMNBos+y+QYgTVXtsPdT+KkDFMsoVW0mV+u76c1Y8nCOG+kdeqk+Yc5Z4/AlALQxtlrUmBh3Q==,iv:WBTh8iR7fAiEAHi0mBHedofl3R820NmUbZdxlVCON9A=,tag:rGbJfV/V3st56RA3zjWW2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uj6pjpu9ma36qg4gzp5guhp68qh9lashjahx39vyry8nsl9np7sz4vcfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOEppWGFJV21BRHErcHFF
            akJQVkFkSGhEOUsxWlc4SmY0bkdTdU4vT1dZCkswU1VZRXVxQi9La2paaVU4RS9i
            R1JHUUtvSmFqYkphbkdvOCtuY3ByOXcKLS0tIGg3dFNEcGdrWEhxWUhDZHA2akNG
            OThhUjZLVXovQ1pwS2g0OE5XQ0Jacm8KCLmUA8zAbtzqUwAZ7AY8F4487xwCjV6J
            4+NKTIzQ19ViZbp8ovGj+LEKzRu85sQbhAuSQMl14CJ3T7Dn2r7g3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrt2jcn6csppu2xjfmzfcy2r922cenvn8gygkrct25mxwelhcpeqzrrj2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNHJvODI1VWQybXlKK1Ix
            ZGhJdlpWcDAxYVlTUFAxRnR4eW5pYU9VUmtnCnFaZDdHd3dvNTM4M1FNRXZLeldj
            VFI1NDdSQW5HbkRVRlVCbjl2QUpVYlkKLS0tIGNTcFJzUWF6b2V1Tll2emNEU1ZG
            QUthYlJmaThDTUdvQWdWK0tBS1dwRjQKNrmR8hYksDNuhOZKE16lWDBNmW3C0Hof
            wQMr92M3i/zs+r3wIzsn5g1StrJ14BNv/tR5q8UbFgJJndrCuqbMvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T14:05:09Z"
    mac: ENC[AES256_GCM,data:plHpSlqIDzAZtFZJ+CuNa2LYEEqfQYcIruMyN4ujn2trDtZFMmoAv4iK88JbO15Xmhvq+sqaoLshRQvAypKdiOKfWitdERS4CtFGihqW/Y5sm07rq4nXKgqVfRBfNOGsSaMJ2baaC+oNOlmUG7PIX6UiecyIYFTTK/SIxdT2ZdM=,iv:JkVryFyAF3o0c42JzgG/TcXcUP4F1HcYGwcHN7rYHl8=,tag:WStz5gQu4KvvIlsmgllz4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
